import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Check, FileText, Pencil, Printer, X } from 'lucide-react';
import { v3Api } from '../../services/v3Api';
import './shopConsole.css';

function jobName(job) { const order = Array.isArray(job.orders) ? job.orders[0] : job.orders; const filename = job.print_artifacts?.source_documents?.original_file_name; return order?.customer_job_name || filename || 'Print document'; }
function optionsFor(job) { const item = Array.isArray(job.price_quote_items) ? job.price_quote_items[0] : job.price_quote_items; const quote = Array.isArray(job.price_quotes) ? job.price_quotes[0] : job.price_quotes; return job.shop_options_override_json || item?.options_json || quote?.options_json || {}; }
function settingsLabel(job) { const o = optionsFor(job); const pages = job.print_artifacts?.logical_page_count; return [`${o.copies || 1} ${Number(o.copies || 1) === 1 ? 'copy' : 'copies'}`, o.color_mode === 'color' ? 'Colour' : 'B&W', o.duplex ? 'Double-sided' : 'Single-sided', pages ? `${pages} pages` : null].filter(Boolean).join(' · '); }
function statusLabel(status) { return ({ printing: 'Printing', completed: 'Completed', rejected: 'Rejected', failed: 'Failed', needs_attention: 'Needs attention', cancelled: 'Cancelled' })[status] || 'Approved'; }

export default function ShopQueue() {
  const navigate = useNavigate(); const [jobs, setJobs] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [, setNotice] = useState(''); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false); const [pendingAction, setPendingAction] = useState(null); const pendingActionRef = useRef(null);
  const fetchQueue = useCallback(async () => { try { const response = await fetch('/api/v3/shop/jobs', { credentials: 'include', headers: { 'X-AutoPrint-Contract-Version': '3' } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`); const freshJobs = data.jobs || []; const pending = pendingActionRef.current; setJobs(previous => { if (!pending) return freshJobs; const previousPending = previous.find(job => job.id === pending.id); if (!previousPending) return freshJobs; const next = freshJobs.filter(job => job.id !== pending.id); const index = Math.min(Math.max(0, previous.findIndex(job => job.id === pending.id)), next.length); next.splice(index, 0, previousPending); return next; }); setError(''); } catch (err) { if (err.message.includes('401')) navigate('/v3/console/login'); else setError('The live queue could not be refreshed. It will retry automatically.'); } finally { setLoading(false); } }, [navigate]);
  useEffect(() => { fetchQueue(); const timer = setInterval(fetchQueue, 3000); return () => clearInterval(timer); }, [fetchQueue]);
  const active = useMemo(() => jobs.filter(j => j.status === 'waiting_for_shop' && !j.approved_at), [jobs]); const recent = useMemo(() => jobs.filter(j => !(j.status === 'waiting_for_shop' && !j.approved_at)).slice(0, 30), [jobs]);
  const act = async (job, action) => { if (pendingActionRef.current) return; const pending = { id: job.id, action }; pendingActionRef.current = pending; setPendingAction(pending); setNotice(''); setError(''); try { const csrf = sessionStorage.getItem('v3_csrf') || ''; const response = action === 'approve' ? await fetch(`/api/v3/shop/jobs/${job.id}/approve`, { method: 'POST', credentials: 'include', headers: { 'X-AutoPrint-Contract-Version': '3', 'X-AutoPrint-CSRF': csrf } }) : await fetch(`/api/v3/shop/jobs/${job.id}/reject`, { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json', 'X-AutoPrint-Contract-Version': '3', 'X-AutoPrint-CSRF': csrf }, body: JSON.stringify({}) }); if (!response.ok) throw new Error(); pendingActionRef.current = null; setPendingAction(null); setJobs(previous => previous.filter(item => item.id !== job.id)); setNotice(`${action === 'approve' ? 'Approved' : 'Rejected'} · ${jobName(job)}`); } catch { pendingActionRef.current = null; setPendingAction(null); setError(`Could not ${action} this job. Please try again.`); } };
  const saveEdit = async () => { if (!editing) return; setSaving(true); try { await v3Api.updateShopPrintOptions(editing.id, sessionStorage.getItem('v3_csrf') || '', editing.options); setEditing(null); await fetchQueue(); } catch (err) { setError(err.message || 'Could not save print settings.'); } finally { setSaving(false); } };
  const JobCard = ({ job, operational = false }) => { const isPending = pendingAction?.id === job.id; return <article className={`v3-console-card${isPending ? ' is-pending' : ''}`}><div className="v3-console-card-main"><span className="v3-console-file"><FileText size={20} /></span><div><h3 title={jobName(job)}>{jobName(job)}</h3><p>{settingsLabel(job)}</p><small>{isPending ? (pendingAction.action === 'approve' ? 'Approving…' : 'Rejecting…') : operational ? 'Waiting for your confirmation' : statusLabel(job.status)}</small></div></div>{operational ? <div className="v3-console-actions"><button className="v3-console-edit" disabled={Boolean(pendingAction)} onClick={() => setEditing({ id: job.id, name: jobName(job), options: { copies: 1, color_mode: 'bw', duplex: false, page_range: null, orientation: 'auto', fit_mode: 'fit', paper_size: 'A4', ...optionsFor(job) } })}><Pencil size={15} /> Edit</button><button className="v3-console-reject" disabled={Boolean(pendingAction)} onClick={() => act(job, 'reject')}><X size={15} /> {isPending && pendingAction.action === 'reject' ? 'Rejecting…' : 'Reject'}</button><button className="v3-console-approve" disabled={Boolean(pendingAction)} onClick={() => act(job, 'approve')}><Check size={15} /> {isPending && pendingAction.action === 'approve' ? 'Approving…' : 'Approve'}</button></div> : <span className={`v3-console-status ${job.status}`}>{statusLabel(job.status)}</span>}</article>; };
  if (loading) return <div className="v3-shop-container"><p>Loading print console…</p></div>;
  return <div className="v3-shop-container v3-open-console"><header className="v3-open-console-header"><button type="button" onClick={() => navigate(`/v3/console/${sessionStorage.getItem('v3_shop_id')}/dashboard`)}>← Shop dashboard</button><div><span>AutoPrint</span><h1>Open Console</h1><p>Confirm print requests, then let the connected printer handle the job.</p></div></header>{error && <div className="v3-console-error">{error}</div>}<div className="v3-console-grid"><section className="v3-console-pane"><header><div><h2>Active Queue <b>{active.length}</b></h2><p>Requests waiting for your approval</p></div><Printer size={20} /></header><div className="v3-console-list">{active.length ? active.map(job => <JobCard key={job.id} job={job} operational />) : <div className="v3-console-empty"><Printer size={30} /><h3>Queue is clear</h3><p>New customer print requests will appear here.</p></div>}</div></section><section className="v3-console-pane v3-console-recent"><header><div><h2>Recent Prints</h2><p>Approved, rejected and completed requests</p></div></header><div className="v3-console-list">{recent.length ? recent.map(job => <JobCard key={job.id} job={job} />) : <div className="v3-console-empty"><FileText size={30} /><h3>No recent prints</h3><p>Processed requests will be kept here.</p></div>}</div></section></div>{editing && <div className="v3-edit-overlay" role="dialog" aria-modal="true"><form className="v3-edit-modal" onSubmit={e => { e.preventDefault(); saveEdit(); }}><header><div><span>Print settings</span><h2>{editing.name}</h2></div><button type="button" onClick={() => setEditing(null)}>×</button></header><label>Copies<input type="number" min="1" max="100" value={editing.options.copies} onChange={e => setEditing({ ...editing, options: { ...editing.options, copies: Math.max(1, Number(e.target.value) || 1) } })} /></label><label>Colour<select value={editing.options.color_mode} onChange={e => setEditing({ ...editing, options: { ...editing.options, color_mode: e.target.value } })}><option value="bw">Black & white</option><option value="color">Colour</option></select></label><label>Sides<select value={editing.options.duplex ? 'duplex' : 'simplex'} onChange={e => setEditing({ ...editing, options: { ...editing.options, duplex: e.target.value === 'duplex' } })}><option value="simplex">Single-sided</option><option value="duplex">Double-sided</option></select></label><label>Pages <small>Optional</small><input value={editing.options.page_range || ''} placeholder="All pages, or 1-5, 8" onChange={e => setEditing({ ...editing, options: { ...editing.options, page_range: e.target.value || null } })} /></label><footer><button type="button" onClick={() => setEditing(null)}>Cancel</button><button className="v3-console-approve" disabled={saving}>{saving ? 'Saving…' : 'Save settings'}</button></footer></form></div>}</div>;
}
